<?xml version="1.0" encoding="UTF-8"?>
<testsuite hostname="Vlads-MacBook-Pro.local" failures="2" tests="4" name="CustomLoggingTest" time="0.017" errors="0" timestamp="27 Jan 2020 10:52:49 GMT">
  <testcase classname="CustomLoggingTest" name="testMethodTwo" time="0.006">
    <failure type="java.lang.AssertionError" message="expected:&amp;lt;true&amp;gt; but was:&amp;lt;false&amp;gt;">
      <![CDATA[java.lang.AssertionError: expected:<true> but was:<false>
	at CustomLoggingTest.testMethodTwo(CustomLoggingTest.java:18)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:830)
... Removed 14 stack frames]]>
    </failure>
  </testcase>
  <testcase classname="CustomLoggingTest" name="MethodSix" time="0.0">
    <failure type="java.lang.AssertionError" message="expected:&amp;lt;true&amp;gt; but was:&amp;lt;false&amp;gt;">
      <![CDATA[java.lang.AssertionError: expected:<true> but was:<false>
	at CustomLoggingTest.MethodSix(CustomLoggingTest.java:44)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:830)
... Removed 14 stack frames]]>
    </failure>
  </testcase>
  <testcase classname="CustomLoggingTest" name="testMethodThree" time="0.001">
    <skipped/>
  </testcase>
  <testcase classname="CustomLoggingTest" name="testMethodOne" time="0.001"/>
</testsuite>
